### ISSUE TITLE
watchtower updates itself but fails to delete old container and name is messed up after update

### ISSUE THREAD

**Issue by ShlomiD83** [nicholas-fedor/watchtower#1146]
### Describe the bug

Hi @nicholas-fedor ,
I have two servers, each running it's own Watchtower conatainer.
on Both after watchtower updates itself the name ha a random string and I see the following error.

`Detected 3 Watchtower instances - initiating cleanup
Stopped stale container: mGFAoOWlpkSuvGjVcBWnBwFeBSLiyRUt (1ca5815b6b44)
Failed to remove container | container=mGFAoOWlpkSuvGjVcBWnBwFeBSLiyRUtelapsed=5.158402mserror=Error response from daemon: removal of container 1ca5815b6b448d1c80226215cda6f90472c3a1790b3f2e76267d5f25f0e6ce36 is already in progressid=1ca5815b6b44
Stopped stale container: watchtower (bcf813ceeb8a)
Multiple Watchtower instances detected | error=errors occurred while stopping watchtower containers: 1 instances failed to stop`

### Steps to reproduce

try updating watchtower with watchtower.

### Expected behavior

old container should clean up successfully without errors.

### Environment

- Platform -  Raspberry Pi 4B running Raspberry OS Lite x64.
- Architecture - Arm64
- Docker Version - 29.1.3
- Watchtower 1.13.1 using Docker API v1.51

### Your logs

```text
Detected 3 Watchtower instances - initiating cleanup
Stopped stale container: mGFAoOWlpkSuvGjVcBWnBwFeBSLiyRUt (1ca5815b6b44)
Failed to remove container | container=mGFAoOWlpkSuvGjVcBWnBwFeBSLiyRUtelapsed=5.158402mserror=Error response from daemon: removal of container 1ca5815b6b448d1c80226215cda6f90472c3a1790b3f2e76267d5f25f0e6ce36 is already in progressid=1ca5815b6b44
Stopped stale container: watchtower (bcf813ceeb8a)
Multiple Watchtower instances detected | error=errors occurred while stopping watchtower containers: 1 instances failed to stop
```

**Comment by nicholas-fedor** [comment]
Please feel free to provide your Watchtower configuration.

It's normal for Watchtower to change the name of the old Watchtower container to a random string.

The logs that you've shared indicate that there's likely a second new Watchtower container being created, which would certainly trigger the daemon error when they conflict with each other during cleanup of the old Watchtower container.

**Comment by ShlomiD83** [comment]
services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Jerusalem
      - WATCHTOWER_SCHEDULE= * 40 */6 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=**************
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=*****************
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=**************
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*****************
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=**********
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=r**************
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=**************
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=30
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
    restart: unless-stopped

that's the config on both of my servers.

**Comment by ShlomiD83** [comment]
> Please feel free to provide your Watchtower configuration.
> 
> It's normal for Watchtower to change the name of the old Watchtower container to a random string.
> 
> The logs that you've shared indicate that there's likely a second new Watchtower container being created, which would certainly trigger the daemon error when they conflict with each other during cleanup of the old Watchtower container.

from the emails I receive It seems the update is running twice for some reason.

**Comment by bleeblonks** [comment]
I also am running into this issue. Please let me know if you need anything from me as well.

**Comment by ShlomiD83** [comment]
2025-12-23T07:09:11.561505362Z time="2025-12-23T09:09:11+02:00" level=info msg="Watchtower 1.13.1 using Docker API v1.51"
2025-12-23T07:09:11.561633527Z time="2025-12-23T09:09:11+02:00" level=info msg="Using notifications: smtp"
2025-12-23T07:09:11.561649175Z time="2025-12-23T09:09:11+02:00" level=info msg="Next scheduled run: 2025-12-23 12:40:00 IST in 3 hours, 30 minutes, 48 seconds"
2025-12-23T10:40:09.757682427Z time="2025-12-23T12:40:09+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T10:40:19.457357924Z time="2025-12-23T12:40:19+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T10:40:29.735063067Z time="2025-12-23T12:40:29+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T10:40:40.971229436Z time="2025-12-23T12:40:40+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T10:40:50.536341357Z time="2025-12-23T12:40:50+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T10:41:01.524415787Z time="2025-12-23T12:41:01+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:40:10.583555624Z time="2025-12-23T18:40:10+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:40:21.972469912Z time="2025-12-23T18:40:21+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:40:32.593279363Z time="2025-12-23T18:40:32+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:40:42.599128547Z time="2025-12-23T18:40:42+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:40:53.491966495Z time="2025-12-23T18:40:53+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0
2025-12-23T16:41:02.818127004Z time="2025-12-23T18:41:02+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=5 updated=0

The test runs several times instead of one. 

On the second server i see that it runs twice. 
2025-12-23T07:14:00.933554831Z time="2025-12-23T09:14:00+02:00" level=info msg="Watchtower 1.13.1 using Docker API v1.51"
2025-12-23T07:14:00.933690199Z time="2025-12-23T09:14:00+02:00" level=info msg="Using notifications: smtp"
2025-12-23T07:14:00.933703662Z time="2025-12-23T09:14:00+02:00" level=info msg="Next scheduled run: 2025-12-23 12:30:00 IST in 3 hours, 15 minutes, 59 seconds"
2025-12-23T10:30:41.626993276Z time="2025-12-23T12:30:41+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=30 updated=0
2025-12-23T10:31:22.604615299Z time="2025-12-23T12:31:22+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=30 updated=0
2025-12-23T16:30:47.988285284Z time="2025-12-23T18:30:47+02:00" level=info msg="Found new image" container=vaultwarden image="vaultwarden/server:testing-alpine" new_id=10bbc4a09dd9
2025-12-23T16:31:21.656892676Z time="2025-12-23T18:31:21+02:00" level=info msg="Stopping container" container=vaultwarden id=b1f6d9b3ace8 signal=SIGTERM timeout=30s
2025-12-23T16:31:27.790937267Z time="2025-12-23T18:31:27+02:00" level=info msg="Started new container" container=vaultwarden id=b1f6d9b3ace8 new_id=cea98564ded2
2025-12-23T16:31:27.792394223Z time="2025-12-23T18:31:27+02:00" level=info msg="Removing image" image_id=ceb347c12e98 image_name="vaultwarden/server:testing-alpine" notify=yes
2025-12-23T16:31:27.852583484Z time="2025-12-23T18:31:27+02:00" level=info msg="Update session completed" failed=0 notify=no scanned=30 updated=1

**Comment by Druidblack** [comment]
I get the same error. And as before, after the update, the old container is used, not the new one. As a result, the programs are not updated and the space is occupied by old and new containers.

![Image](https://github.com/user-attachments/assets/171938c6-3d3f-4797-b8c9-6bba5bd960c2)

![Image](https://github.com/user-attachments/assets/e3026fe6-d458-42ce-8b1f-cb82f1c8c26f)

**Comment by Druidblack** [comment]
Could these problems be related to the use of an older version of docker (porteiner)?  I have problems updating the containers on the PC where the old version of docker is installed. 
Docker version 27.5.1, build 9f9e405

On Docker version 29.1.3, build f52814d, the containers are updated correctly with the removal of the old ones. Both PCs have the same configuration settings.

version: "3"
services:
  watchtower:
    image: nickfedor/watchtower #containrrr/watchtower
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=demotoken
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://192.168.1.161:8887/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=ApcoceZ3DZDWiBj
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8079:8080
    command: --interval 86400
#    command: --interval 60

**Comment by Druidblack** [comment]
Now I noticed that on docker version 29.1.3, build f52814d, there were problems updating the WATCHTOWER program, it updated the container, neo continued to use the old version, trying to create a new one.

**Comment by nicholas-fedor** [comment]
@Druidblack This is always a possibility, along with the use of a particular configuration option in Portainer, or some other edge case that has been missed.

I will continue to work on this, but expect no further releases until after the start of the new year.

**Comment by lcombs15** [comment]
Following, same issue as a couple weeks ago it seems 

I’ve seen it create a handful of containers on self update

**Comment by mrmuiz** [comment]
<img width="1171" height="878" alt="Image" src="https://github.com/user-attachments/assets/ac10a68c-123e-4c54-8551-e11b995399ff" /> It messed up most containers.

**Comment by cstout1** [comment]
Adding a "me too" here to follow since my portainer looks just like mrmuiz' screenshot above.

**Comment by jackc94** [comment]
Adding a “me too” here as well.

**Comment by SteveS801** [comment]
<img width="2241" height="1083" alt="Image" src="https://github.com/user-attachments/assets/8be01845-47f6-4eee-8e7c-90ddac9d2463" />
Another "me too" over here. 8411 containers, when maybe 11-15 are my own.

**Comment by Nindaleth** [comment]
Guys, there's 9 people subscribed to the issue now and every additional "me too" spams each of them with an additional email. You can reach all necessary results even without the added spam and annoyance:

* if you want to let the world know you suffer from the issue too, put a thumbs up emoji to the first issue comment (point 1 in the screen below).
* if _you_ want to get future updates on the issue, click the "Subscribe" button (point 2 in the screen below).

This is standard GitHub netiquette, not something specific to this repo.

<img width="1272" height="1269" alt="Image" src="https://github.com/user-attachments/assets/dae3433f-2c86-4074-8a63-095bbdc89107" />

**Comment by Serpensin** [comment]
It's not quite the same issue for me, as it is for others. My containers don't shutdown! Right now, I just noticed, that I have over 100 instances running at the same time and some, that are trying to start.
I only noticed it, because my hoster keeps restarting the VPS every day or so.


<img width="1043" height="918" alt="Image" src="https://github.com/user-attachments/assets/9e47f4e8-edb1-4689-bccb-6700922f0b84" />

<img width="1083" height="316" alt="Image" src="https://github.com/user-attachments/assets/31500d1f-cd93-43f9-8de5-75257258e727" />

**Comment by mrmuiz** [comment]
I tried to recreate my containers. But i had to see the log files wich container it was before recreate. After i did a few, all others where fixed  like magic without recreate.  No clue how  this happend. But its all up and running again.

**Comment by nicholas-fedor** [comment]
During testing, I observed that running Watchtower alongside Portainer, combined with intermittent system slowdowns, appeared to trigger race conditions. This prevented Watchtower from properly cleaning up old (parent) containers, leading to cases where the new Watchtower container performed updates against the old one and spawned additional orphaned containers. 

The changes in https://github.com/nicholas-fedor/watchtower/pull/1159 are expected to resolve these self-update issues and initial testing indicates the issue is resolved. Given that the self-update issues have persisted despite prior fixes, I'm keeping this issue open until the fix is released — currently targeted for Tuesday, January 6th. 


If you'd like to provide feedback, the `nickfedor/watchtower:latest-dev` image is available for testing. It's updated regularly and offers a good way to verify that self-updates behave as expected.

**Comment by bleeblonks** [comment]
> During testing, I observed that running Watchtower alongside Portainer, combined with intermittent system slowdowns, appeared to trigger race conditions. This prevented Watchtower from properly cleaning up old (parent) containers, leading to cases where the new Watchtower container performed updates against the old one and spawned additional orphaned containers.
> 
> The changes in [#1159](https://github.com/nicholas-fedor/watchtower/pull/1159) are expected to resolve these self-update issues and initial testing indicates the issue is resolved. Given that the self-update issues have persisted despite prior fixes, I'm keeping this issue open until the fix is released — currently targeted for Tuesday, January 6th.
> 
> If you'd like to provide feedback, the `nickfedor/watchtower:latest-dev` image is available for testing. It's updated regularly and offers a good way to verify that self-updates behave as expected.

I will be testing, just changed 2 nodes to this image and will check back in a little.

**Comment by ShlomiD83** [comment]
@nicholas-fedor updated to the dev image but the issue wasn't resolved. 
It tried to update itself a few minutes ago and the problem persists.

**Comment by nicholas-fedor** [comment]
@ShlomiD83 Any further information that you can provide regarding the behavior you observed?

**Comment by ShlomiD83** [comment]
> [@ShlomiD83](https://github.com/ShlomiD83) Any further information that you can provide regarding the behavior you observed?

both servers are Raspberry Pi 4B running Raspberry Pi OS lite x64 based on debian Bookworm, the problem is just with Watchtower updating itself, other containers update just fine, no duplicates with weird names.

**Comment by ZoltrixGFC** [comment]
@nicholas-fedor sorry dude, same result here. I have two separate docker servers. Changed both watchtower instances to `nickfedor/watchtower:latest-dev` yesterday, deleted all of the orphaned containers, etc.

But today, both have orphaned ones created again.

These are both Ubuntu servers running as VMs on separate Proxmox hosts.

<img width="1014" height="492" alt="Image" src="https://github.com/user-attachments/assets/d574a7de-6bb5-4828-8544-50c697bc48ea" />

<img width="976" height="308" alt="Image" src="https://github.com/user-attachments/assets/fd215c5b-d141-4f19-a26c-5f5edcb2f699" />

**Comment by nicholas-fedor** [comment]
I appreciate the feedback and will be continuing to develop stronger mechanisms to mitigate this issue.

**Comment by ShlomiD83** [comment]
@nicholas-fedor Just happened again, but I've noticed that if watchtower updates itself and another container, it detects 2 instances and deletes the old instance and the name is ok. 
If watchtower updates ONLY itself It detects 3 instances and deletes the first created + the old instance and leave the newest with the weird name.

**Comment by ShlomiD83** [comment]
@nicholas-fedor watchtower updtaed itself twice now without issues, but instead of 1 email it sends 3, what can we to about it? 
1. Found new image: nickfedor/watchtower:latest-dev (36b04b204fee)
Started new container: watchtower (becda776cc75)


2. Found new image: nickfedor/watchtower:latest-dev (36b04b204fee)

3. Stopped stale container: watchtower-old-1d77679d1559 (1d77679d1559)
Cleaned up old image: nickfedor/watchtower:latest-dev (2da327887e2f)
Successfully removed 1 excess Watchtower instance

These are the messages that i received from one server, the sent the same emails except for the second email.

**Comment by mateusz-bajorek** [comment]
Today, with the 1.14.1 release, the watchtower container after self-update got into this state:

<img width="1334" height="105" alt="Image" src="https://github.com/user-attachments/assets/f7d0ce60-0de5-4721-b664-b49feffd4bd2" />

**Comment by gabry45** [comment]
Same for me, but the container named "...-old-..." was started and the original one was stopped instead. And it did not delete the old image.
@ShlomiD83 is it still working as expected for you? If not, could you please reopen this issue?

**Comment by ShlomiD83** [comment]
> Same for me, but the container named "...-old-..." was started and the original one was stopped instead. And it did not delete the old image. [@ShlomiD83](https://github.com/ShlomiD83) is it still working as expected for you? If not, could you please reopen this issue?

The update process works, the multiple notifications are the "problem" now.

**Comment by azurecrash** [comment]
Checking in. Same. I've experienced this with watchtower updating itself and multiple other apps and services. In an attempt to reduce the effort of cleaning things up, I've delayed update schedules to 1 week for each watchtower instance (5 servers). If helpful, it is worth noting that I did not experience this prior to the fork. I wonder if, therefore, new functionality introduced this bug. Thanks!

**Comment by ShlomiD83** [comment]
@nicholas-fedor 
`Context canceled while waiting for running update`
Started getting emails with this message during Watchtower self update, on both servers.

**Comment by lluisd** [comment]
I have the same problem, watchtower it fails most of the times when it needs to update itself

here my logs:
``` 
2026-03-25 04:12:53.900 info [watchtower] time="2026-03-25T04:12:53+01:00" level=info msg="Stopping container" container=watchtower id=a6d295bb0955 signal=SIGTERM timeout=30s 
2026-03-25 04:12:56.360 info [watchtower] time="2026-03-25T04:12:56+01:00" level=info msg="Initiating HTTP server shutdown due to context cancellation" 
2026-03-25 04:12:56.485 warn [watchtower] time="2026-03-25T04:12:56+01:00" level=warning msg="Context canceled while waiting for running update." 
```

**Comment by nicholas-fedor** [comment]
This issue is being inappropriately used as a catch-all for problems related to self-updates.
If you are experiencing issues, then please report them correctly.

**Comment by nicholas-fedor** [comment]
@lluisd If you are using the HTTP API and mapping a port for Watchtower, then self-updates are going to fail. This is an architectural issue, where Docker cannot release ports while a container is still running.

**Comment by nicholas-fedor** [comment]
@ShlomiD83 #1491 provides the option to use a short-lived container to orchestrate the self-update process. Despite being experimental, I'm hoping that it provides a more reliable method for self-updates and should alleviate many of the problems noted in this thread.
