### ISSUE TITLE
Error response from daemon: page not found

### ISSUE THREAD

**Issue by xstrex** [nicholas-fedor/watchtower#303]
### Describe the bug

Watchtower container constantly restarting. 
```
time="2025-06-06T22:53:44Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T22:53:44Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-06T22:53:50Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T22:53:50Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-06T22:53:56Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T22:53:56Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-06T22:54:02Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T22:54:02Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
```

### Steps to reproduce

Install container using docker-compose, utilizing HTTP API/Token, and version compatible with Synology NAS. 
```yaml
  watchtower:
    container_name: Watchtower
    restart: unless-stopped
    image: nickfedor/watchtower
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    environment:
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_HTTP_API_TOKEN=<redacted>
      - WATCHTOWER_HTTP_API_METRICS=true
      - DOCKER_API_VERSION="1.43"
    ports:
      - 8080:8080
```

### Expected behavior

Container to start-up and operate normally. 

### Environment

- Platform
    - Synology Nas: DS1817+
    - DSM: 7.2.2-72806 Update 3
- Architecture: linux/amd64
- Docker Version
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        610b8d0
 Built:             Wed Feb  5 11:08:05 2025
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       bd0a34d
  Built:            Wed Feb  5 11:06:45 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        067f5021280b8de2059026fb5c43c4adb0f3f244
 runc:
  Version:          v1.1.7
  GitCommit:        0320c58
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00

### Your logs

```text
time="2025-06-06T23:04:23Z" level=debug msg="Configured logging settings" fields.level=debug format=auto no_color=false
time="2025-06-06T23:04:23Z" level=debug msg="Retrieved operational flags" cleanup=true monitor_only=false no_restart=false timeout=10s
time="2025-06-06T23:04:23Z" level=debug msg="Set environment variable" env=DOCKER_HOST value="unix:///var/run/docker.sock"
time="2025-06-06T23:04:23Z" level=debug msg="Configured Docker environment variables" host="unix:///var/run/docker.sock" tls=false version="\"1.43\""
time="2025-06-06T23:04:23Z" level=debug msg="Initialized Docker client" opts="{RemoveVolumes:false IncludeStopped:false ReviveStopped:false IncludeRestarting:false DisableMemorySwappiness:false WarnOnHeadFailed:}" version="\"1.43\""
time="2025-06-06T23:04:23Z" level=debug msg="Parsing notifications log level" fields.level=info
time="2025-06-06T23:04:23Z" level=debug msg="Retrieving template data" hostname_flag=
time="2025-06-06T23:04:23Z" level=debug msg="Using system hostname" hostname=93b0c99cec8a hostname_flag=
time="2025-06-06T23:04:23Z" level=debug msg="Using legacy email subject tag" hostname_flag= tag=
time="2025-06-06T23:04:23Z" level=debug msg="Generating notification title" hostname=93b0c99cec8a tag=
time="2025-06-06T23:04:23Z" level=debug msg="Generated notification title" hostname=93b0c99cec8a tag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:23Z" level=debug msg="Populated template data" hostname=93b0c99cec8a hostname_flag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:23Z" level=debug msg="Appending legacy notification URLs" function=AppendLegacyUrls
time="2025-06-06T23:04:23Z" level=debug msg="Processing legacy notification types" function=AppendLegacyUrls types="[]"
time="2025-06-06T23:04:23Z" level=debug msg="Determining notification delay" legacy_delay=0s
time="2025-06-06T23:04:23Z" level=debug msg="No delay configured, using zero" legacy_delay=0s
time="2025-06-06T23:04:23Z" level=debug msg="Completed legacy URL appending" delay=0s function=AppendLegacyUrls urls="[]"
time="2025-06-06T23:04:23Z" level=debug msg="Creating notifier with configuration" delay=0s fields.level=info hostname=93b0c99cec8a skip_report=true stdout=false template= title="Watchtower updates on 93b0c99cec8a" urls="[]"
time="2025-06-06T23:04:23Z" level=debug msg="Added Shoutrrr notifier as logrus hook, starting notification goroutine" notify=no urls="[]"
time="2025-06-06T23:04:23Z" level=debug msg="Building container filter" disableNames="[]" enableLabel=false names="[]" scope=
time="2025-06-06T23:04:23Z" level=debug msg="Filter built" disableNames="[]" enableLabel=false filter_desc="Checking all containers (except explicitly disabled with label)" names="[]" scope=
time="2025-06-06T23:04:23Z" level=debug msg="Processing specified containers" names="[]"
time="2025-06-06T23:04:23Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2025-06-06T23:04:24Z" level=debug msg="Performing pre-update sanity checks"
time="2025-06-06T23:04:24Z" level=debug msg="Retrieving container list" include_restarting=false include_stopped=false
time="2025-06-06T23:04:24Z" level=debug msg="Failed to list containers" error="Error response from daemon: page not found" include_restarting=false include_stopped=false
time="2025-06-06T23:04:24Z" level=debug msg="Failed to list containers" error="failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:24Z" level=debug msg="Failed to list containers" error="failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:24Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:24Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-06T23:04:24Z" level=debug msg="Exiting with non-zero status" exit_code=1
time="2025-06-06T23:04:31Z" level=debug msg="Configured logging settings" fields.level=debug format=auto no_color=false
time="2025-06-06T23:04:31Z" level=debug msg="Retrieved operational flags" cleanup=true monitor_only=false no_restart=false timeout=10s
time="2025-06-06T23:04:31Z" level=debug msg="Set environment variable" env=DOCKER_HOST value="unix:///var/run/docker.sock"
time="2025-06-06T23:04:31Z" level=debug msg="Configured Docker environment variables" host="unix:///var/run/docker.sock" tls=false version="\"1.43\""
time="2025-06-06T23:04:31Z" level=debug msg="Initialized Docker client" opts="{RemoveVolumes:false IncludeStopped:false ReviveStopped:false IncludeRestarting:false DisableMemorySwappiness:false WarnOnHeadFailed:}" version="\"1.43\""
time="2025-06-06T23:04:31Z" level=debug msg="Parsing notifications log level" fields.level=info
time="2025-06-06T23:04:31Z" level=debug msg="Retrieving template data" hostname_flag=
time="2025-06-06T23:04:31Z" level=debug msg="Using system hostname" hostname=93b0c99cec8a hostname_flag=
time="2025-06-06T23:04:31Z" level=debug msg="Using legacy email subject tag" hostname_flag= tag=
time="2025-06-06T23:04:31Z" level=debug msg="Generating notification title" hostname=93b0c99cec8a tag=
time="2025-06-06T23:04:31Z" level=debug msg="Generated notification title" hostname=93b0c99cec8a tag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:31Z" level=debug msg="Populated template data" hostname=93b0c99cec8a hostname_flag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:31Z" level=debug msg="Appending legacy notification URLs" function=AppendLegacyUrls
time="2025-06-06T23:04:31Z" level=debug msg="Processing legacy notification types" function=AppendLegacyUrls types="[]"
time="2025-06-06T23:04:31Z" level=debug msg="Determining notification delay" legacy_delay=0s
time="2025-06-06T23:04:31Z" level=debug msg="No delay configured, using zero" legacy_delay=0s
time="2025-06-06T23:04:31Z" level=debug msg="Completed legacy URL appending" delay=0s function=AppendLegacyUrls urls="[]"
time="2025-06-06T23:04:31Z" level=debug msg="Creating notifier with configuration" delay=0s fields.level=info hostname=93b0c99cec8a skip_report=true stdout=false template= title="Watchtower updates on 93b0c99cec8a" urls="[]"
time="2025-06-06T23:04:31Z" level=debug msg="Added Shoutrrr notifier as logrus hook, starting notification goroutine" notify=no urls="[]"
time="2025-06-06T23:04:31Z" level=debug msg="Building container filter" disableNames="[]" enableLabel=false names="[]" scope=
time="2025-06-06T23:04:31Z" level=debug msg="Filter built" disableNames="[]" enableLabel=false filter_desc="Checking all containers (except explicitly disabled with label)" names="[]" scope=
time="2025-06-06T23:04:31Z" level=debug msg="Processing specified containers" names="[]"
time="2025-06-06T23:04:31Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2025-06-06T23:04:32Z" level=debug msg="Performing pre-update sanity checks"
time="2025-06-06T23:04:32Z" level=debug msg="Retrieving container list" include_restarting=false include_stopped=false
time="2025-06-06T23:04:32Z" level=debug msg="Failed to list containers" error="Error response from daemon: page not found" include_restarting=false include_stopped=false
time="2025-06-06T23:04:32Z" level=debug msg="Failed to list containers" error="failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:32Z" level=debug msg="Failed to list containers" error="failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:32Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:32Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-06T23:04:32Z" level=debug msg="Exiting with non-zero status" exit_code=1
time="2025-06-06T23:04:38Z" level=debug msg="Configured logging settings" fields.level=debug format=auto no_color=false
time="2025-06-06T23:04:38Z" level=debug msg="Retrieved operational flags" cleanup=true monitor_only=false no_restart=false timeout=10s
time="2025-06-06T23:04:38Z" level=debug msg="Set environment variable" env=DOCKER_HOST value="unix:///var/run/docker.sock"
time="2025-06-06T23:04:38Z" level=debug msg="Configured Docker environment variables" host="unix:///var/run/docker.sock" tls=false version="\"1.43\""
time="2025-06-06T23:04:38Z" level=debug msg="Initialized Docker client" opts="{RemoveVolumes:false IncludeStopped:false ReviveStopped:false IncludeRestarting:false DisableMemorySwappiness:false WarnOnHeadFailed:}" version="\"1.43\""
time="2025-06-06T23:04:38Z" level=debug msg="Parsing notifications log level" fields.level=info
time="2025-06-06T23:04:38Z" level=debug msg="Retrieving template data" hostname_flag=
time="2025-06-06T23:04:38Z" level=debug msg="Using system hostname" hostname=93b0c99cec8a hostname_flag=
time="2025-06-06T23:04:38Z" level=debug msg="Using legacy email subject tag" hostname_flag= tag=
time="2025-06-06T23:04:38Z" level=debug msg="Generating notification title" hostname=93b0c99cec8a tag=
time="2025-06-06T23:04:38Z" level=debug msg="Generated notification title" hostname=93b0c99cec8a tag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:38Z" level=debug msg="Populated template data" hostname=93b0c99cec8a hostname_flag= title="Watchtower updates on 93b0c99cec8a"
time="2025-06-06T23:04:38Z" level=debug msg="Appending legacy notification URLs" function=AppendLegacyUrls
time="2025-06-06T23:04:38Z" level=debug msg="Processing legacy notification types" function=AppendLegacyUrls types="[]"
time="2025-06-06T23:04:38Z" level=debug msg="Determining notification delay" legacy_delay=0s
time="2025-06-06T23:04:38Z" level=debug msg="No delay configured, using zero" legacy_delay=0s
time="2025-06-06T23:04:38Z" level=debug msg="Completed legacy URL appending" delay=0s function=AppendLegacyUrls urls="[]"
time="2025-06-06T23:04:38Z" level=debug msg="Creating notifier with configuration" delay=0s fields.level=info hostname=93b0c99cec8a skip_report=true stdout=false template= title="Watchtower updates on 93b0c99cec8a" urls="[]"
time="2025-06-06T23:04:38Z" level=debug msg="Added Shoutrrr notifier as logrus hook, starting notification goroutine" notify=no urls="[]"
time="2025-06-06T23:04:38Z" level=debug msg="Building container filter" disableNames="[]" enableLabel=false names="[]" scope=
time="2025-06-06T23:04:38Z" level=debug msg="Filter built" disableNames="[]" enableLabel=false filter_desc="Checking all containers (except explicitly disabled with label)" names="[]" scope=
time="2025-06-06T23:04:38Z" level=debug msg="Processing specified containers" names="[]"
time="2025-06-06T23:04:38Z" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2025-06-06T23:04:39Z" level=debug msg="Performing pre-update sanity checks"
time="2025-06-06T23:04:39Z" level=debug msg="Retrieving container list" include_restarting=false include_stopped=false
time="2025-06-06T23:04:39Z" level=debug msg="Failed to list containers" error="Error response from daemon: page not found" include_restarting=false include_stopped=false
time="2025-06-06T23:04:39Z" level=debug msg="Failed to list containers" error="failed to list containers: Error response from daemon: page not found"
time="2025-06-06T23:04:39Z" level=debug msg="Exiting with non-zero status" exit_code=1
```

**Comment by nicholas-fedor** [comment]
After some initial testing, this appears to be related to the `DOCKER_API_VERSION` variable.
Interestingly, I was able to generate this error using both current and prior Watchtower release versions on both older and updated Docker hosts by simply the inclusion of the variable.

**Comment by nicholas-fedor** [comment]
@xstrex I just released v1.11.0, which should take care of things.
Definitely let me know if you encounter anymore issues.

**Comment by xstrex** [comment]
@nicholas-fedor Thanks for the commit; I see that you're now auto-negotiating by default, which is great! 

I did try excluding the DOCKER_API_VERSION to allow auto-negotiating to work, though it still failed, and produced similar errors in the logs:
```
time="2025-06-07T12:47:16Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43"
time="2025-06-07T12:47:16Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-07T12:47:18Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43"
time="2025-06-07T12:47:18Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-07T12:47:22Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43"
time="2025-06-07T12:47:22Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
time="2025-06-07T12:47:24Z" level=error msg="Sanity check failed" error="failed to list containers: failed to list containers: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43"
time="2025-06-07T12:47:24Z" level=info msg="Waiting for the notification goroutine to finish" notify=no
```

I then added DOCKER_API_VERSION back, and it seems to be working this time; though I excluded the `"` around the version. 
```yaml
  watchtower:
    container_name: Watchtower
    restart: unless-stopped
    image: nickfedor/watchtower:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    environment:
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true # Jabba NetMon Stack
      - WATCHTOWER_HTTP_API_TOKEN=<redacted>
      - WATCHTOWER_HTTP_API_METRICS=true
      - DOCKER_API_VERSION=1.43
    ports:
      - 8480:8080
```

and this seems to of worked.. 
```
time="2025-06-07T12:56:08Z" level=info msg="Starting HTTP API server" addr=":8080"
time="2025-06-07T12:56:08Z" level=info msg="Watchtower 1.10.0 using Docker API v1.43"
time="2025-06-07T12:56:08Z" level=info msg="Using no notifications"
time="2025-06-07T12:56:08Z" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2025-06-07T12:56:08Z" level=info msg="Scheduling first run: 2025-06-08 00:56:08 +0000 UTC"
time="2025-06-07T12:56:08Z" level=info msg="Note that the first check will be performed in 11 hours, 59 minutes, 59 seconds"
```

So, failed successfully?

**Comment by nicholas-fedor** [comment]
Looks like you're still using v1.10.0; however, as you discovered, the issue was the usage of the quotations.

**Comment by xstrex** [comment]
For my own knowledge, was the variable expecting a float and not a string? Since 1.43 != "1.43".

**Comment by nicholas-fedor** [comment]
String. As for the quotations, it's an easy mistake that even I didn't initially catch. Docker's Compose reference is helpful in highlighting this: https://docs.docker.com/reference/compose-file/services/#environment
